### ISSUE TITLE
Training Problem

### ISSUE THREAD

**Issue by back95126** [DingHsun/AI-CUP-Competition#1]
HI , im also a taiwan student
For this competition I have some issue
how can i contact with u.

**Comment by DingHsun** [comment]
可以直接這個信箱聯絡！

back95126 ***@***.***>於 2022年11月21日 週一，14:10寫道：

**Comment by back95126** [comment]
你好,
我有試著執行您的程式碼
針對dataset的部分 主要好奇data.zip這個壓縮檔 我該上傳些什麼東西

另外,雖然有些無理不知道能不能向您索取較差的performance的csv檔作為上傳依據
因為其實參加這個比賽主要只是因應課堂上的一個報告

黃鼎勳 ***@***.***> 於 2022年11月21日 週一 下午2:15寫道：

**Comment by DingHsun** [comment]
1.  data.zip已上傳至我的專案。主要是yolo要讀取的資料路徑及class數量的參數文本。
2. 若想要訓練自己的網路可以更改「yolov5x模型訓練」的code並執行，
*!python /content/yolov5/train.py --data ./data.yaml --cfg
/content/yolov5/models/yolov5x.yaml --batch-size -1 --epochs 50 --rect
--imgsz 1080 --image-weights*
若想要較輕量的網路可以更改 */content/yolov5/models/yolov5x.yaml* 為你想要的model。
3.關於索取較差的performance的csv檔，如果不想自行訓練可以私下用個人信箱私訊我。

back95126 ***@***.***> 於 2022年11月21日 週一 下午2:24寫道：

**Comment by back95126** [comment]
非常謝謝您的回答
我會試著訓練看看

csv檔的部分 我有成功產生了

再次謝謝您
